version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    # Look for `action.yml` and `workflow` files in the `.github` directory
    directory: "/"
    # Check the GitHub API for updates once a week
    schedule:
      interval: "weekly"
